### ISSUE TITLE
Make context available to remote schema

### ISSUE THREAD

**Issue by BassT** [kbrandwijk/graphql-gateway-tools#1]
For passing context to a remote schema the [guide](https://www.apollographql.com/docs/graphql-tools/remote-schemas.html#link-api) suggest to pass context as HTTP headers using the Link API.

Feature suggestion:
- `schemaTools.forwardHeader("someHeader")`
- `schemaTools.forwardContext("context.someContext")`

**Comment by kbrandwijk** [comment]
Thank you for your suggestion. I will evaluate it in my new GraphQL Application Framework: [Qewl](https://github.com/kbrandwijk/qewl).
